import type { InstalledPerformanceFixtureManifest } from "./installedPerformanceFixtureManifestTypes";

export const FIXTURE_COLUMN_NAME_PATTERN: "c followed by a zero-padded zero-based integer";
export const FIXTURE_COLUMN_TYPE: "Int64";
export const FIXTURE_REDISTRIBUTION: "Deterministic synthetic integer fixtures generated by Open Wrangler.";
export const INSTALLED_PERFORMANCE_FIXTURE_PROTOCOL: "openwrangler-installed-performance-fixtures-v1";

export function decodeInstalledPerformanceFixtureManifest(value: unknown): InstalledPerformanceFixtureManifest;
