export type InstalledPerformanceFixtureFormat = "csv" | "parquet";

export interface InstalledPerformanceFixtureEntry {
  fileName: string;
  format: InstalledPerformanceFixtureFormat;
  rows: number;
  columns: number;
  columnType: "Int64";
  columnNamePattern: "c followed by a zero-padded zero-based integer";
  sentinelRows: [number, number, number];
  sha256: string;
  bytes: number;
}

export interface InstalledPerformanceFixtureManifest {
  protocol: "openwrangler-installed-performance-fixtures-v1";
  smoke: boolean;
  generator: {
    contractVersion: 1;
    implementation: "polars";
    implementationVersion: string;
  };
  license: "CC0-1.0";
  redistribution: "Deterministic synthetic integer fixtures generated by Open Wrangler.";
  fixtures: {
    csv: InstalledPerformanceFixtureEntry & { format: "csv" };
    parquet: InstalledPerformanceFixtureEntry & { format: "parquet" };
  };
}
