const INSTALLED_PERFORMANCE_FIXTURE_PROTOCOL = "openwrangler-installed-performance-fixtures-v1";
const FIXTURE_COLUMN_TYPE = "Int64";
const FIXTURE_COLUMN_NAME_PATTERN = "c followed by a zero-padded zero-based integer";
const FIXTURE_REDISTRIBUTION = "Deterministic synthetic integer fixtures generated by Open Wrangler.";
const SHA256 = /^[0-9a-f]{64}$/u;

function decodeInstalledPerformanceFixtureManifest(value) {
  exactKeys(value, ["protocol", "smoke", "generator", "license", "redistribution", "fixtures"], "fixture manifest");
  assertEqual(value.protocol, INSTALLED_PERFORMANCE_FIXTURE_PROTOCOL, "fixture manifest protocol");
  if (typeof value.smoke !== "boolean") {
    throw new TypeError("fixture manifest smoke flag must be a boolean.");
  }
  exactKeys(value.generator, ["contractVersion", "implementation", "implementationVersion"], "fixture generator");
  assertEqual(value.generator.contractVersion, 1, "fixture generator contract version");
  assertEqual(value.generator.implementation, "polars", "fixture generator implementation");
  assertBoundedString(value.generator.implementationVersion, "fixture generator version");
  assertEqual(value.license, "CC0-1.0", "fixture license");
  assertEqual(value.redistribution, FIXTURE_REDISTRIBUTION, "fixture redistribution statement");
  exactKeys(value.fixtures, ["csv", "parquet"], "fixture entries");

  const expected = value.smoke
    ? { csv: [2_000, 8], parquet: [5_000, 8] }
    : { csv: [100_000, 50], parquet: [1_000_000, 20] };
  for (const format of ["csv", "parquet"]) {
    validateFixtureEntry(value.fixtures[format], format, ...expected[format]);
  }
  return value;
}

function validateFixtureEntry(entry, format, rows, columns) {
  exactKeys(
    entry,
    ["fileName", "format", "rows", "columns", "columnType", "columnNamePattern", "sentinelRows", "sha256", "bytes"],
    `${format} fixture`
  );
  assertEqual(entry.fileName, `${rows}-${columns}.${format}`, `${format} fixture file name`);
  assertEqual(entry.format, format, `${format} fixture format`);
  assertEqual(entry.rows, rows, `${format} fixture rows`);
  assertEqual(entry.columns, columns, `${format} fixture columns`);
  assertEqual(entry.columnType, FIXTURE_COLUMN_TYPE, `${format} fixture column type`);
  assertEqual(entry.columnNamePattern, FIXTURE_COLUMN_NAME_PATTERN, `${format} fixture column-name pattern`);
  const sentinels = [0, Math.floor(rows / 2), rows - 1];
  if (
    !Array.isArray(entry.sentinelRows) ||
    entry.sentinelRows.length !== sentinels.length ||
    entry.sentinelRows.some((value, index) => value !== sentinels[index])
  ) {
    throw new TypeError(`${format} fixture sentinel rows do not match the deterministic contract.`);
  }
  if (typeof entry.sha256 !== "string" || !SHA256.test(entry.sha256)) {
    throw new TypeError(`${format} fixture SHA-256 is invalid.`);
  }
  if (!Number.isSafeInteger(entry.bytes) || entry.bytes <= 0) {
    throw new TypeError(`${format} fixture byte size must be positive.`);
  }
}

function exactKeys(value, expected, label) {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object.`);
  }
  const actual = Object.keys(value).sort();
  const canonicalExpected = [...expected].sort();
  if (actual.length !== canonicalExpected.length || actual.some((key, index) => key !== canonicalExpected[index])) {
    throw new TypeError(`${label} has missing or unknown fields.`);
  }
}

function assertBoundedString(value, label) {
  if (typeof value !== "string" || value.length === 0 || value.length > 256 || /[\0\r\n]/u.test(value)) {
    throw new TypeError(`${label} must be one bounded single-line string.`);
  }
}

function assertEqual(actual, expected, label) {
  if (actual !== expected) {
    throw new TypeError(`${label} must be ${JSON.stringify(expected)}.`);
  }
}

module.exports = {
  FIXTURE_COLUMN_NAME_PATTERN,
  FIXTURE_COLUMN_TYPE,
  FIXTURE_REDISTRIBUTION,
  INSTALLED_PERFORMANCE_FIXTURE_PROTOCOL,
  decodeInstalledPerformanceFixtureManifest
};
