export const PACKAGED_SCREENSHOT_COLUMNS = [
  "order_id",
  "market",
  "revenue",
  "fulfilled",
  "order_date",
  "segment",
  "channel",
  "product_family",
  "units",
  "unit_price",
  "discount_pct",
  "gross_margin",
  "priority",
  "renewal_date",
  "account_note"
] as const;
export const PACKAGED_SCREENSHOT_ROW_COUNT = 10_000;
export const PACKAGED_SCREENSHOT_MARKETS = [
  "Benelux",
  "DACH",
  "France",
  "Iberia",
  "Italy",
  "Nordics",
  "UK & Ireland"
] as const;
export const PACKAGED_SCREENSHOT_SCENES = ["hero", "transform"] as const;
export const PACKAGED_SCREENSHOT_FEATURED_COLUMNS = [
  "order_id",
  "market",
  "revenue",
  "fulfilled",
  "order_date"
] as const satisfies readonly (typeof PACKAGED_SCREENSHOT_COLUMNS)[number][];
export const PACKAGED_SCREENSHOT_FIXED_FEATURED_WIDTHS = {
  order_id: 160,
  market: 160,
  revenue: 195,
  fulfilled: 170
} as const;
export const PACKAGED_SCREENSHOT_DATA_PROVENANCE =
  "Deterministic synthetic order data generated by Open Wrangler; no external or private source data.";

const DAY_MS = 86_400_000;
const FIRST_ORDER_DATE_UTC = Date.UTC(2024, 0, 1);
const SEGMENTS = ["Enterprise", "Mid-market", "Public sector", "Small business"] as const;
const CHANNELS = ["Direct", "Online", "Partner"] as const;
const PRODUCT_FAMILIES = ["Analytics", "Automation", "Data platform", "Operations", "Planning"] as const;
const PRIORITIES = ["High", "Standard", "Strategic"] as const;
const ACCOUNT_NOTES = [
  'Renewal review follows the Q2 pilot, with "steady adoption" reported across the regional account',
  "Expansion opportunity spans analytics and planning workflows with a staged rollout requested",
  "Implementation is on track after the accessibility review and regional enablement sessions",
  "Procurement requested a consolidated proposal covering support levels and implementation milestones",
  "Customer success flagged strong adoption while the data-governance workstream remains in progress"
] as const;

export function packagedScreenshotFixtureCsv(): string {
  const lines = [PACKAGED_SCREENSHOT_COLUMNS.map(csvCell).join(",")];
  for (let index = 0; index < PACKAGED_SCREENSHOT_ROW_COUNT; index += 1) {
    lines.push(packagedScreenshotRow(index).map(csvCell).join(","));
  }
  return `${lines.join("\n")}\n`;
}

export function packagedScreenshotRow(index: number): readonly string[] {
  if (!Number.isSafeInteger(index) || index < 0 || index >= PACKAGED_SCREENSHOT_ROW_COUNT) {
    throw new RangeError("Screenshot fixture row index is out of range.");
  }
  const marketIndex = (index * 5 + Math.floor(index / 17)) % PACKAGED_SCREENSHOT_MARKETS.length;
  const orderId = 2_400_001 + index;
  const units = 1 + ((index * 11 + marketIndex * 3) % 24);
  const unitPriceCents = 7_900 + ((index * 7_919 + marketIndex * 31_337) % 92_000);
  const discountBasisPoints = (index * 37 + marketIndex * 73) % 1_800;
  const revenueCents = Math.round((units * unitPriceCents * (10_000 - discountBasisPoints)) / 10_000);
  const revenue = (index + 29) % 113 === 0 ? "" : (revenueCents / 100).toFixed(2);
  const unitCount = (index + 19) % 149 === 0 ? "" : String(units);
  const fulfilled = (index + 41) % 197 === 0 ? "" : (index * 13 + marketIndex * 7) % 20 < 17 ? "true" : "false";
  const dayOffset = (index * 17 + Math.floor(index / 11)) % 730;
  const orderDate = (index + 67) % 251 === 0 ? "" : isoDate(FIRST_ORDER_DATE_UTC + dayOffset * DAY_MS);
  const renewalDate =
    fulfilled === "false" || (index + 13) % 9 === 0
      ? ""
      : isoDate(FIRST_ORDER_DATE_UTC + (dayOffset + 365 + ((index * 7) % 61)) * DAY_MS);
  const grossMargin =
    revenue === "" ? "" : ((revenueCents * (2_400 + ((index * 19 + marketIndex * 41) % 3_200))) / 1_000_000).toFixed(2);
  const note = (index + 23) % 11 === 0 ? "" : ACCOUNT_NOTES[(index * 3 + marketIndex) % ACCOUNT_NOTES.length];
  return [
    String(orderId),
    PACKAGED_SCREENSHOT_MARKETS[marketIndex],
    revenue,
    fulfilled,
    orderDate,
    SEGMENTS[(index * 3 + marketIndex) % SEGMENTS.length],
    CHANNELS[(index * 7 + marketIndex) % CHANNELS.length],
    PRODUCT_FAMILIES[(index * 11 + marketIndex) % PRODUCT_FAMILIES.length],
    unitCount,
    (unitPriceCents / 100).toFixed(2),
    (index + 71) % 181 === 0 ? "" : (discountBasisPoints / 100).toFixed(2),
    grossMargin,
    PRIORITIES[(index * 5 + marketIndex) % PRIORITIES.length],
    renewalDate,
    note
  ];
}

export function packagedScreenshotFeaturedColumnWidths(
  gridClientWidth: number,
  rowHeaderWidth: number
): Readonly<Record<(typeof PACKAGED_SCREENSHOT_FEATURED_COLUMNS)[number], number>> {
  if (
    !Number.isFinite(gridClientWidth) ||
    !Number.isFinite(rowHeaderWidth) ||
    gridClientWidth <= 0 ||
    rowHeaderWidth <= 0
  ) {
    throw new TypeError("Screenshot grid dimensions must be finite positive numbers.");
  }
  const fixedWidth = Object.values(PACKAGED_SCREENSHOT_FIXED_FEATURED_WIDTHS).reduce(
    (total, width) => total + width,
    0
  );
  const orderDateWidth = Math.floor(gridClientWidth - rowHeaderWidth - fixedWidth);
  if (orderDateWidth < 160 || orderDateWidth > 640) {
    throw new RangeError("Screenshot grid cannot fit the featured columns without clipping.");
  }
  return { ...PACKAGED_SCREENSHOT_FIXED_FEATURED_WIDTHS, order_date: orderDateWidth };
}

export function packagedScreenshotFileName(
  editor: string,
  scene: (typeof PACKAGED_SCREENSHOT_SCENES)[number],
  theme: "dark" | "light"
): string {
  if (!/^[a-z][a-z0-9-]{0,31}$/u.test(editor)) {
    throw new TypeError("Screenshot editor keys must be short lowercase identifiers.");
  }
  return `${editor}-${scene}-${theme}.png`;
}

function csvCell(value: string): string {
  return /[",\r\n]/u.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
}

function isoDate(timestamp: number): string {
  return new Date(timestamp).toISOString().slice(0, 10);
}
