export const PACKAGED_SCREENSHOT_COLUMNS = [
  "order_id",
  "market",
  "revenue",
  "fulfilled",
  "order_date",
  "segment",
  "channel",
  "product_family",
  "units",
  "unit_price",
  "discount_pct",
  "gross_margin",
  "priority",
  "renewal_date",
  "account_note"
] as const;
export const PACKAGED_SCREENSHOT_ROW_COUNT = 100_000;
export const PACKAGED_FIRST_USE_ROW_COUNT = 10_000;
export const PACKAGED_WIDE_SCHEMA_COLUMN_COUNT = 417;
export const PACKAGED_WIDE_SCHEMA_ROW_COUNT = 64;
export const PACKAGED_SCREENSHOT_VIEWPORT = { width: 1_920, height: 860 } as const;
export const PACKAGED_NOTEBOOK_WORKBENCH_VIEWPORT = { width: 1_440, height: 900 } as const;
export const PACKAGED_PRODUCT_VIEWPORT = { width: 1_440, height: 900 } as const;
export const PACKAGED_OPERATION_DIALOG_VIEWPORT = { width: 1_280, height: 900 } as const;
export const PACKAGED_PANDAS_NOTEBOOK_VIEWPORT = { width: 1_280, height: 700 } as const;
export const PACKAGED_PANDAS_NOTEBOOK_OUTPUT = { width: 1_280, height: 600 } as const;
export const PACKAGED_SCREENSHOT_MARKETS = [
  "Benelux",
  "DACH",
  "France",
  "Iberia",
  "Italy",
  "Nordics",
  "UK & Ireland"
] as const;
export const PACKAGED_SCREENSHOT_SCENES = [
  "hero",
  "explore",
  "filter-result",
  "workflow",
  "sidebar-overview",
  "operation-catalog",
  "operation-configuration",
  "applied-step-inspection",
  "notebook-pandas",
  "notebook-variable-picker",
  "notebook-pyspark-picker",
  "notebook-polars",
  "notebook-duckdb",
  "notebook-pyspark"
] as const;
export const PACKAGED_SCREENSHOT_FEATURED_COLUMNS = [
  "order_id",
  "market",
  "revenue",
  "fulfilled",
  "order_date"
] as const satisfies readonly (typeof PACKAGED_SCREENSHOT_COLUMNS)[number][];
export const PACKAGED_SCREENSHOT_MINIMUM_FEATURED_WIDTHS = {
  order_id: 160,
  market: 160,
  revenue: 195,
  fulfilled: 170,
  order_date: 210
} as const;
const PACKAGED_SCREENSHOT_FEATURED_EXPANSION_WEIGHTS = {
  order_id: 3,
  market: 3,
  revenue: 3,
  fulfilled: 3,
  order_date: 8
} as const;
export const PACKAGED_SCREENSHOT_DATA_PROVENANCE =
  "Deterministic synthetic order data generated by Open Wrangler; no external or private source data.";

const DAY_MS = 86_400_000;
const FIRST_ORDER_DATE_UTC = Date.UTC(2024, 0, 1);
const SEGMENTS = ["Enterprise", "Mid-market", "Public sector", "Small business"] as const;
const CHANNELS = ["Direct", "Online", "Partner"] as const;
const PRODUCT_FAMILIES = ["Analytics", "Automation", "Data platform", "Operations", "Planning"] as const;
const PRIORITIES = ["High", "Standard", "Strategic"] as const;
const ACCOUNT_NOTES = [
  'Renewal review follows the Q2 pilot, with "steady adoption" reported across the regional account',
  "Expansion opportunity spans analytics and planning workflows with a staged rollout requested",
  "Implementation is on track after accessibility reviews and enablement sessions in Zürich and São Paulo",
  "Procurement requested a consolidated proposal covering support levels and implementation milestones",
  "Customer success flagged strong adoption while the data-governance workstream remains in progress"
] as const;

export function packagedScreenshotFixtureCsv(): string {
  const lines = [PACKAGED_SCREENSHOT_COLUMNS.map(csvCell).join(",")];
  for (let index = 0; index < PACKAGED_SCREENSHOT_ROW_COUNT; index += 1) {
    lines.push(packagedScreenshotRow(index).map(csvCell).join(","));
  }
  return `${lines.join("\n")}\n`;
}

export function packagedFirstUseFixtureCsv(): string {
  return packagedSemicolonFixtureCsv(PACKAGED_FIRST_USE_ROW_COUNT);
}

/**
 * Builds the larger, realistic file used only by final product-scene capture.
 * First-use editor journeys deliberately keep their independent 10,000-row
 * fixture so validating launch surfaces does not inherit screenshot overhead.
 */
export function packagedProductFixtureCsv(): string {
  return packagedSemicolonFixtureCsv(PACKAGED_SCREENSHOT_ROW_COUNT);
}

function packagedSemicolonFixtureCsv(rowCount: number): string {
  const delimiter = ";";
  const lines = [
    `\uFEFF${PACKAGED_SCREENSHOT_COLUMNS.map((value) => delimitedCell(value, delimiter)).join(delimiter)}`
  ];
  for (let index = 0; index < rowCount; index += 1) {
    const accountNoteKind = packagedFirstUseAccountNoteKind(index);
    lines.push(
      packagedScreenshotRow(index)
        .map((value, columnIndex) =>
          columnIndex === PACKAGED_SCREENSHOT_COLUMNS.length - 1 && accountNoteKind === "empty"
            ? '""'
            : delimitedCell(value, delimiter)
        )
        .join(delimiter)
    );
  }
  return `${lines.join("\n")}\n`;
}

const WIDE_SCHEMA_LEADING_COLUMNS = [
  "account_id",
  "account_name",
  "billing_country",
  "contract_start_date",
  "contract_end_date",
  "customer_segment",
  "product_family",
  "subscription_status",
  "annual_revenue_usd",
  "renewal_probability",
  "usage_score",
  "data_quality_flag"
] as const;
const WIDE_SCHEMA_DOMAINS = [
  "account",
  "billing",
  "contract",
  "customer",
  "forecast",
  "product",
  "quality",
  "region",
  "subscription",
  "usage"
] as const;
const WIDE_SCHEMA_MEASURES = ["amount", "count", "date", "flag", "score", "status", "value"] as const;

export function packagedWideSchemaColumns(): readonly string[] {
  const columns: string[] = [...WIDE_SCHEMA_LEADING_COLUMNS];
  for (let position = columns.length; position < PACKAGED_WIDE_SCHEMA_COLUMN_COUNT; position += 1) {
    const ordinal = position + 1;
    const domain = WIDE_SCHEMA_DOMAINS[Math.floor(position / WIDE_SCHEMA_MEASURES.length) % WIDE_SCHEMA_DOMAINS.length];
    const measure = WIDE_SCHEMA_MEASURES[position % WIDE_SCHEMA_MEASURES.length];
    columns.push(`${domain}_${measure}_${String(ordinal).padStart(3, "0")}`);
  }
  return columns;
}

export function packagedWideSchemaFixtureCsv(): string {
  const columns = packagedWideSchemaColumns();
  const lines = [columns.map(csvCell).join(",")];
  for (let row = 0; row < PACKAGED_WIDE_SCHEMA_ROW_COUNT; row += 1) {
    lines.push(
      columns
        .map((_, position) => {
          if (position === 0) return `ACCT-${String(row + 1).padStart(5, "0")}`;
          if (position === 1) return `Synthetic account ${row + 1}`;
          if (position === 2) return ["DE", "FR", "IT", "NL", "SE", "UK"][row % 6]!;
          if (position === 3) return isoDate(Date.UTC(2024, row % 12, 1));
          if (position === 4) return isoDate(Date.UTC(2026, row % 12, 1));
          if (position === 5) return ["Enterprise", "Mid-market", "Public sector"][row % 3]!;
          if (position === 6) return ["Analytics", "Automation", "Planning"][row % 3]!;
          if (position === 7) return ["Active", "Expansion", "Renewal review"][row % 3]!;
          if (position === 8) return String(250_000 + row * 7_500);
          if (position === 9) return ((row * 13) % 101).toFixed(2);
          if (position === 10) return ((row * 17) % 101).toFixed(2);
          if (position === 11) return row % 7 !== 0 ? "true" : "false";
          const measure = WIDE_SCHEMA_MEASURES[position % WIDE_SCHEMA_MEASURES.length];
          switch (measure) {
            case "amount":
              return (1_000 + (((row + 3) * (position + 11)) % 9_000_000) / 100).toFixed(2);
            case "count":
              return String(((row + 3) * (position + 11)) % 50_003);
            case "date":
              return isoDate(Date.UTC(2023 + (row % 4), (row + position) % 12, 1 + ((row + position) % 27)));
            case "flag":
              return (row + position) % 3 === 0 ? "true" : "false";
            case "score":
              return ((((row + 5) * (position + 7)) % 10_001) / 100).toFixed(2);
            case "status":
              return ["Active", "At risk", "Paused", "Review"][row % 4]!;
            case "value":
              return `segment-${String(((row + 1) * (position + 3)) % 97).padStart(2, "0")}`;
          }
        })
        .map(csvCell)
        .join(",")
    );
  }
  return `${lines.join("\n")}\n`;
}

export function packagedFirstUseAccountNoteKind(index: number): "value" | "empty" | "null" {
  const value = packagedScreenshotRow(index)[PACKAGED_SCREENSHOT_COLUMNS.length - 1];
  if (value !== "") return "value";
  // Alternate absent notes between an explicit quoted empty string and an
  // unquoted missing field. The installed-editor journey therefore proves
  // that real CSV parsing and Insights preserve the user-visible distinction.
  return index % 2 === 0 ? "empty" : "null";
}

export function packagedScreenshotRow(index: number): readonly string[] {
  if (!Number.isSafeInteger(index) || index < 0 || index >= PACKAGED_SCREENSHOT_ROW_COUNT) {
    throw new RangeError("Screenshot fixture row index is out of range.");
  }
  const marketIndex = (index * 5 + Math.floor(index / 17)) % PACKAGED_SCREENSHOT_MARKETS.length;
  const orderId = 2_400_001 + index;
  const units = 1 + ((index * 11 + marketIndex * 3) % 24);
  const unitPriceCents = 7_900 + ((index * 7_919 + marketIndex * 31_337) % 92_000);
  const discountBasisPoints = (index * 37 + marketIndex * 73) % 1_800;
  const revenueCents = Math.round((units * unitPriceCents * (10_000 - discountBasisPoints)) / 10_000);
  const revenue = (index + 29) % 113 === 0 ? "" : (revenueCents / 100).toFixed(2);
  const unitCount = (index + 19) % 149 === 0 ? "" : String(units);
  const fulfilled = (index + 41) % 197 === 0 ? "" : (index * 13 + marketIndex * 7) % 20 < 17 ? "true" : "false";
  const dayOffset = (index * 17 + Math.floor(index / 11)) % 730;
  const orderDate = (index + 67) % 251 === 0 ? "" : isoDate(FIRST_ORDER_DATE_UTC + dayOffset * DAY_MS);
  const renewalDate =
    fulfilled === "false" || (index + 13) % 9 === 0
      ? ""
      : isoDate(FIRST_ORDER_DATE_UTC + (dayOffset + 365 + ((index * 7) % 61)) * DAY_MS);
  const grossMargin =
    revenue === "" ? "" : ((revenueCents * (2_400 + ((index * 19 + marketIndex * 41) % 3_200))) / 1_000_000).toFixed(2);
  const note = (index + 23) % 11 === 0 ? "" : ACCOUNT_NOTES[(index * 3 + marketIndex) % ACCOUNT_NOTES.length];
  return [
    String(orderId),
    PACKAGED_SCREENSHOT_MARKETS[marketIndex],
    revenue,
    fulfilled,
    orderDate,
    SEGMENTS[(index * 3 + marketIndex) % SEGMENTS.length],
    CHANNELS[(index * 7 + marketIndex) % CHANNELS.length],
    PRODUCT_FAMILIES[(index * 11 + marketIndex) % PRODUCT_FAMILIES.length],
    unitCount,
    (unitPriceCents / 100).toFixed(2),
    (index + 71) % 181 === 0 ? "" : (discountBasisPoints / 100).toFixed(2),
    grossMargin,
    PRIORITIES[(index * 5 + marketIndex) % PRIORITIES.length],
    renewalDate,
    note
  ];
}

export function packagedScreenshotFeaturedColumnWidths(
  gridClientWidth: number,
  rowHeaderWidth: number
): Readonly<Record<(typeof PACKAGED_SCREENSHOT_FEATURED_COLUMNS)[number], number>> {
  if (
    !Number.isFinite(gridClientWidth) ||
    !Number.isFinite(rowHeaderWidth) ||
    gridClientWidth <= 0 ||
    rowHeaderWidth <= 0
  ) {
    throw new TypeError("Screenshot grid dimensions must be finite positive numbers.");
  }
  const availableWidth = Math.floor(gridClientWidth - rowHeaderWidth);
  const minimumWidth = Object.values(PACKAGED_SCREENSHOT_MINIMUM_FEATURED_WIDTHS).reduce(
    (total, width) => total + width,
    0
  );
  const maximumWidth = PACKAGED_SCREENSHOT_FEATURED_COLUMNS.length * 640;
  if (availableWidth < minimumWidth || availableWidth > maximumWidth) {
    throw new RangeError("Screenshot grid cannot fit the featured columns without clipping.");
  }
  const widths = { ...PACKAGED_SCREENSHOT_MINIMUM_FEATURED_WIDTHS } as Record<
    (typeof PACKAGED_SCREENSHOT_FEATURED_COLUMNS)[number],
    number
  >;
  let remaining = availableWidth - minimumWidth;
  while (remaining > 0) {
    const expandable = PACKAGED_SCREENSHOT_FEATURED_COLUMNS.filter((name) => widths[name] < 640);
    if (expandable.length === 0) {
      throw new RangeError("Screenshot grid cannot fit the featured columns without clipping.");
    }
    const passRemaining = remaining;
    const totalWeight = expandable.reduce(
      (total, name) => total + PACKAGED_SCREENSHOT_FEATURED_EXPANSION_WEIGHTS[name],
      0
    );
    let allocated = 0;
    for (const name of expandable) {
      const planned = Math.max(
        1,
        Math.floor((passRemaining * PACKAGED_SCREENSHOT_FEATURED_EXPANSION_WEIGHTS[name]) / totalWeight)
      );
      const increment = Math.min(planned, 640 - widths[name], remaining);
      widths[name] += increment;
      remaining -= increment;
      allocated += increment;
      if (remaining === 0) break;
    }
    if (allocated === 0) {
      throw new RangeError("Screenshot grid cannot fit the featured columns without clipping.");
    }
  }
  return widths;
}

export function packagedScreenshotFileName(
  editor: string,
  scene: (typeof PACKAGED_SCREENSHOT_SCENES)[number],
  theme: "dark" | "light"
): string {
  if (!/^[a-z][a-z0-9-]{0,31}$/u.test(editor)) {
    throw new TypeError("Screenshot editor keys must be short lowercase identifiers.");
  }
  return `${editor}-${scene}-${theme}.png`;
}

function csvCell(value: string): string {
  return delimitedCell(value, ",");
}

function delimitedCell(value: string, delimiter: string): string {
  return value.includes(delimiter) || /["\r\n]/u.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
}

function isoDate(timestamp: number): string {
  return new Date(timestamp).toISOString().slice(0, 10);
}
