from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Literal, TypedDict, cast

import polars as pl
import pytest

python_root = Path(__file__).parents[1]
sys.path.insert(0, str(python_root))
try:
    from benchmarks import fixture_contract
finally:
    sys.path.remove(str(python_root))


class _FixtureEvidence(TypedDict):
    fileName: str
    format: Literal["csv", "parquet"]
    rows: int
    columns: int
    columnType: Literal["Int64"]
    columnNamePattern: str
    sentinelRows: list[int]
    bytes: int
    sha256: str


class _GeneratorEvidence(TypedDict):
    contractVersion: int
    implementation: Literal["polars"]
    implementationVersion: str


class _FixtureManifest(TypedDict):
    protocol: str
    smoke: bool
    generator: _GeneratorEvidence
    license: str
    redistribution: str
    fixtures: dict[str, _FixtureEvidence]


def test_installed_editor_fixture_manifest_is_deterministic_and_path_free(tmp_path: Path) -> None:
    first = _generate(tmp_path / "first")
    second = _generate(tmp_path / "second")

    assert first == second
    assert first["protocol"] == "openwrangler-installed-performance-fixtures-v1"
    assert first["smoke"] is True
    assert first["generator"]["contractVersion"] == 1
    assert first["generator"]["implementation"] == "polars"
    assert first["generator"]["implementationVersion"]
    assert first["license"] == "CC0-1.0"
    assert first["redistribution"] == "Deterministic synthetic integer fixtures generated by Open Wrangler."
    assert set(first["fixtures"]) == {"csv", "parquet"}
    assert first["fixtures"]["csv"]["rows"] == 2_000
    assert first["fixtures"]["csv"]["columns"] == 8
    assert first["fixtures"]["parquet"]["rows"] == 5_000
    assert first["fixtures"]["parquet"]["columns"] == 8
    serialized = json.dumps(first, sort_keys=True)
    assert str(tmp_path) not in serialized
    assert "c00" not in serialized

    for directory_name in ("first", "second"):
        directory = tmp_path / directory_name / "fixtures"
        for evidence in first["fixtures"].values():
            source = directory / evidence["fileName"]
            assert source.is_file()
            assert source.stat().st_size == evidence["bytes"]
            assert hashlib.sha256(source.read_bytes()).hexdigest() == evidence["sha256"]


def test_python_smoke_manifest_passes_the_extension_host_decoder(tmp_path: Path) -> None:
    payload, generated_output = _generate_with_output(tmp_path / "host-contract")
    node = shutil.which("node")
    assert node is not None
    decoder = Path(__file__).parents[2] / "src" / "shared" / "installedPerformanceFixtureManifest.cjs"
    decoder_program = (
        "const fs = require('node:fs');"
        "const contract = require(process.argv[1]);"
        "const strictJson = require(process.argv[2]);"
        "const value = contract.decodeInstalledPerformanceFixtureManifest("
        "strictJson.parseStrictJson(fs.readFileSync(0, 'utf8'), { maxBytes: 65536 }));"
        "process.stdout.write(JSON.stringify(value));"
    )
    strict_json = Path(__file__).parents[2] / "src" / "shared" / "strictJson.cjs"
    result = subprocess.run(
        [node, "-e", decoder_program, str(decoder), str(strict_json)],
        input=generated_output,
        check=True,
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert cast(_FixtureManifest, json.loads(result.stdout)) == payload


def test_installed_editor_fixture_generation_rejects_a_symlink_target(tmp_path: Path) -> None:
    root = tmp_path / "fixtures"
    root.mkdir()
    outside = tmp_path / "outside.csv"
    outside.write_text("do-not-overwrite\n", encoding="utf-8")
    (root / "2000-8.csv").symlink_to(outside)
    manifest = tmp_path / "manifest.json"

    result = subprocess.run(
        [
            sys.executable,
            str(_fixture_script()),
            "--smoke",
            "--output-dir",
            str(root),
            "--manifest-out",
            str(manifest),
        ],
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )

    assert result.returncode != 0
    assert "single-link regular file" in result.stderr
    assert outside.read_text(encoding="utf-8") == "do-not-overwrite\n"
    assert not manifest.exists()


def test_existing_invalid_fixtures_are_atomically_regenerated_and_fully_validated(tmp_path, monkeypatch) -> None:
    fixtures = fixture_contract.create_fixtures(tmp_path, smoke=True)
    specs = fixture_contract.fixture_specs(smoke=True)

    csv_spec = specs["csv"]
    invalid_csv = pl.DataFrame(
        {name: pl.int_range(column, csv_spec.rows + column, eager=True) for column, name in enumerate(csv_spec.names)}
    ).with_row_index("row")
    interior_row = csv_spec.rows // 2 + 17
    assert interior_row not in csv_spec.sentinel_rows
    invalid_csv = invalid_csv.with_columns(
        pl.when(pl.col("row") == interior_row).then(pl.lit(-1)).otherwise(pl.col("c03")).alias("c03")
    ).drop("row")
    invalid_csv.write_csv(fixtures["csv"])
    pl.DataFrame({"wrong": ["schema"]}).write_parquet(fixtures["parquet"])

    replacements: list[tuple[Path, Path]] = []
    real_replace = fixture_contract.os.replace

    def observe_replace(source: str | Path, destination: str | Path) -> None:
        replacements.append((Path(source), Path(destination)))
        real_replace(source, destination)

    monkeypatch.setattr(fixture_contract.os, "replace", observe_replace)
    repaired = fixture_contract.create_fixtures(tmp_path, smoke=True)

    assert {destination for _, destination in replacements} == {fixtures["csv"], fixtures["parquet"]}
    assert all(source.parent == tmp_path and source.name.startswith(".") for source, _ in replacements)
    for kind, path in repaired.items():
        fixture_contract.assert_fixture_contract(path, specs[kind])


@pytest.mark.parametrize("kind", ["csv", "parquet"])
def test_fixture_contract_rejects_an_interior_value_tamper(tmp_path: Path, kind: Literal["csv", "parquet"]) -> None:
    spec = fixture_contract.FixtureSpec(kind, rows=101, columns=4)
    interior_row = 37
    assert interior_row not in spec.sentinel_rows
    frame = pl.DataFrame(
        {name: pl.int_range(column, spec.rows + column, eager=True) for column, name in enumerate(spec.names)}
    ).with_row_index("row")
    frame = frame.with_columns(
        pl.when(pl.col("row") == interior_row).then(pl.lit(-1)).otherwise(pl.col("c02")).alias("c02")
    ).drop("row")
    path = tmp_path / f"tampered.{kind}"
    if kind == "csv":
        frame.write_csv(path)
    else:
        frame.write_parquet(path)

    with pytest.raises(AssertionError, match="invalid value counts by column"):
        fixture_contract.assert_fixture_contract(path, spec)


def test_semantically_equal_csv_with_different_newlines_has_different_bytes(tmp_path: Path) -> None:
    spec = fixture_contract.FixtureSpec("csv", rows=101, columns=4)
    frame = pl.DataFrame(
        {name: pl.int_range(column, spec.rows + column, eager=True) for column, name in enumerate(spec.names)}
    )
    canonical = tmp_path / "canonical.csv"
    alternate = tmp_path / "alternate.csv"
    frame.write_csv(canonical)
    alternate.write_bytes(canonical.read_bytes().replace(b"\n", b"\r\n"))

    fixture_contract.assert_fixture_contract(canonical, spec)
    fixture_contract.assert_fixture_contract(alternate, spec)
    assert hashlib.sha256(canonical.read_bytes()).digest() != hashlib.sha256(alternate.read_bytes()).digest()


def test_semantically_equal_parquet_layout_has_different_bytes(tmp_path: Path) -> None:
    spec = fixture_contract.FixtureSpec("parquet", rows=101, columns=4)
    frame = pl.DataFrame(
        {name: pl.int_range(column, spec.rows + column, eager=True) for column, name in enumerate(spec.names)}
    )
    canonical = tmp_path / "canonical.parquet"
    alternate = tmp_path / "alternate.parquet"
    frame.write_parquet(canonical)
    frame.write_parquet(alternate, compression="uncompressed", row_group_size=17)

    fixture_contract.assert_fixture_contract(canonical, spec)
    fixture_contract.assert_fixture_contract(alternate, spec)
    assert hashlib.sha256(canonical.read_bytes()).digest() != hashlib.sha256(alternate.read_bytes()).digest()


def _generate(root: Path) -> _FixtureManifest:
    payload, _ = _generate_with_output(root)
    return payload


def _generate_with_output(root: Path) -> tuple[_FixtureManifest, str]:
    fixture_directory = root / "fixtures"
    manifest = root / "manifest.json"
    result = subprocess.run(
        [
            sys.executable,
            str(_fixture_script()),
            "--smoke",
            "--output-dir",
            str(fixture_directory),
            "--manifest-out",
            str(manifest),
        ],
        check=True,
        capture_output=True,
        text=True,
        timeout=30,
    )
    payload = cast(_FixtureManifest, json.loads(result.stdout))
    assert json.loads(manifest.read_text(encoding="utf-8")) == payload
    return payload, result.stdout


def _fixture_script() -> Path:
    return Path(__file__).parents[1] / "benchmarks" / "installed_editor_fixtures.py"
